classDiagram
    КлассПользователя <|-- КлассАдминистратора
    КлассПользователя : +имя string
    КлассПользователя : +email string
    КлассПользователя : +зарегистрироваться()
    КлассПользователя : +войти(email:string, пароль:string):boolean
    
    КлассАдминистратора : +создатьПост(заголовок:string, контент:string):void
    КлассАдминистратора : +редактироватьПост(id:int, новыйКонтент:string):void
